/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Pedidos (void)
{
  GtkWidget *Pedidos;
  GtkWidget *vbox2;
  GtkWidget *table1;
  GtkWidget *fixed1;
  GtkWidget *viewport1;
  GtkWidget *lblCumplidos;
  GtkWidget *viewport2;
  GtkWidget *lblAtrasados;
  GtkWidget *viewport3;
  GtkWidget *lblPedidosEntregados;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *viewport4;
  GtkWidget *lblPedidos;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeViewPedidos;

  Pedidos = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Pedidos), _("Pedidos pendientes"));
  gtk_window_set_position (GTK_WINDOW (Pedidos), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (Pedidos), 800, 600);
  gtk_window_set_gravity (GTK_WINDOW (Pedidos), GDK_GRAVITY_EAST);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (Pedidos), vbox2);

  table1 = gtk_table_new (1, 3, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, FALSE, FALSE, 0);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_table_attach (GTK_TABLE (table1), fixed1, 0, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (fixed1, 800, 115);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_fixed_put (GTK_FIXED (fixed1), viewport1, 440, 48);
  gtk_widget_set_size_request (viewport1, 136, 64);

  lblCumplidos = gtk_label_new (_("<span size=\"36000\" color=\"#338823\"><b>0</b></span>"));
  gtk_widget_show (lblCumplidos);
  gtk_container_add (GTK_CONTAINER (viewport1), lblCumplidos);
  gtk_label_set_use_markup (GTK_LABEL (lblCumplidos), TRUE);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_fixed_put (GTK_FIXED (fixed1), viewport2, 656, 48);
  gtk_widget_set_size_request (viewport2, 132, 64);

  lblAtrasados = gtk_label_new (_("<span size=\"36000\" color=\"#AA2822\"><b>0</b></span>"));
  gtk_widget_show (lblAtrasados);
  gtk_container_add (GTK_CONTAINER (viewport2), lblAtrasados);
  gtk_label_set_use_markup (GTK_LABEL (lblAtrasados), TRUE);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_fixed_put (GTK_FIXED (fixed1), viewport3, 240, 48);
  gtk_widget_set_size_request (viewport3, 132, 64);

  lblPedidosEntregados = gtk_label_new (_("<span size=\"36000\" color=\"#222888\"><b>0</b></span>"));
  gtk_widget_show (lblPedidosEntregados);
  gtk_container_add (GTK_CONTAINER (viewport3), lblPedidosEntregados);
  gtk_label_set_use_markup (GTK_LABEL (lblPedidosEntregados), TRUE);

  label9 = gtk_label_new_with_mnemonic (_("<span size=\"19000\" color=\"#d0b520\"><b>Cumplidos</b></span>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 408, 8);
  gtk_widget_set_size_request (label9, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label9), TRUE);

  label10 = gtk_label_new (_("<span size=\"19000\" color=\"#d0b520\"><b>Atrasados</b></span>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 608, 8);
  gtk_widget_set_size_request (label10, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label10), TRUE);

  label13 = gtk_label_new (_("<span size=\"19000\" color=\"#d0b520\"><b>Pedidos del dia</b></span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 8, 8);
  gtk_widget_set_size_request (label13, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label13), TRUE);

  label15 = gtk_label_new_with_mnemonic (_("<span size=\"19000\" color=\"#d0b520\"><b>Entregados</b></span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed1), label15, 208, 8);
  gtk_widget_set_size_request (label15, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label15), TRUE);

  viewport4 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport4);
  gtk_fixed_put (GTK_FIXED (fixed1), viewport4, 40, 48);
  gtk_widget_set_size_request (viewport4, 132, 64);

  lblPedidos = gtk_label_new (_("<span size=\"36000\" ><b>0</b></span>"));
  gtk_widget_show (lblPedidos);
  gtk_container_add (GTK_CONTAINER (viewport4), lblPedidos);
  gtk_label_set_use_markup (GTK_LABEL (lblPedidos), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);

  treeViewPedidos = gtk_tree_view_new ();
  gtk_widget_show (treeViewPedidos);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeViewPedidos);

  g_signal_connect ((gpointer) Pedidos, "show",
                    G_CALLBACK (on_Pedidos_show),
                    NULL);
  g_signal_connect ((gpointer) Pedidos, "destroy",
                    G_CALLBACK (on_Pedidos_destroy),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Pedidos, Pedidos, "Pedidos");
  GLADE_HOOKUP_OBJECT (Pedidos, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (Pedidos, table1, "table1");
  GLADE_HOOKUP_OBJECT (Pedidos, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Pedidos, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (Pedidos, lblCumplidos, "lblCumplidos");
  GLADE_HOOKUP_OBJECT (Pedidos, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (Pedidos, lblAtrasados, "lblAtrasados");
  GLADE_HOOKUP_OBJECT (Pedidos, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (Pedidos, lblPedidosEntregados, "lblPedidosEntregados");
  GLADE_HOOKUP_OBJECT (Pedidos, label9, "label9");
  GLADE_HOOKUP_OBJECT (Pedidos, label10, "label10");
  GLADE_HOOKUP_OBJECT (Pedidos, label13, "label13");
  GLADE_HOOKUP_OBJECT (Pedidos, label15, "label15");
  GLADE_HOOKUP_OBJECT (Pedidos, viewport4, "viewport4");
  GLADE_HOOKUP_OBJECT (Pedidos, lblPedidos, "lblPedidos");
  GLADE_HOOKUP_OBJECT (Pedidos, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Pedidos, treeViewPedidos, "treeViewPedidos");

  return Pedidos;
}

